Update iproj.json and update/create .ibmi.json
IBM/ibmi-bob pull request #269
Opened 2023-11-14 21:49 UTC by irfanshar

2023-11-16 20:27 UTC, edmundreinhardt commented on src/makei/ibmi_json.py
> +        if self.build["tgt_ccsid"] != DEFAULT_TGT_CCSID and self.build["tgt_ccsid"] != "":
is there any chance that it could be `undefined` instead of `""`

2023-11-16 20:27 UTC, edmundreinhardt commented on src/makei/init_project.py
> +    signal.signal(signal.SIGINT, _signal_handler)
Why the signal handler?

2023-11-16 20:27 UTC, edmundreinhardt commented on src/makei/init_project.py
> +                    update_json_field(ibmi_json_path, "build", objlib, "objlib")
no need to duplicate `objlib` in .ibmi.json.  Setting it in `iproj.json` is good enough

2023-11-16 20:27 UTC, edmundreinhardt commented on src/makei/init_project.py
> +                    update_json_field(ibmi_json_path, "build", objlib, "objlib")
In fact I just tested and the .ibmi.json is ignored if both iproj.json and .ibmi.json's objlib are specified

2023-11-16 20:27 UTC, edmundreinhardt commented on src/makei/init_project.py
> +                    update_json_field(ibmi_json_path, "build", objlib, "objlib")
Please remove .ibmi.json/objlib

2023-11-17 14:36 UTC, irfanshar commented on src/makei/init_project.py
> +    signal.signal(signal.SIGINT, _signal_handler)
To handle when the user enters Ctrl+C, and to inform them that the makei init was cancelled

2023-11-17 20:30 UTC, edmundreinhardt requested changes
see my many comments on the objlib commit

2023-11-17 20:30 UTC, edmundreinhardt commented on src/makei/ibmi_json.py
> +        if self.build["tgt_ccsid"] != DEFAULT_TGT_CCSID and self.build["tgt_ccsid"] != None:
probably should guard against either, if it is possible to store "" as a value in Json then we should not consider the value specified

2023-11-24 23:04 UTC, edmundreinhardt requested changes

2023-11-24 23:04 UTC, edmundreinhardt commented on src/makei/build.py
> +        dir_var_map = {Path('.'): IBMiJson.from_values(self.iproj_json.tgt_ccsid)}
we are still consider the parents objlib when computing the current directory object lib, right?
I am confused why objlib is being removed here?

2023-11-24 23:04 UTC, edmundreinhardt commented on src/makei/init_project.py
> +def update_json_field(pathToJsonFile: str, updateKey1: str, updateVal: str, updateKey2: str = "") -> None:
So what are the semantices.  IF the value is "" do we not add the key-value pair?  What about if it is undefined?
Is there a way to delete the field if the `undefined` or empty string is specified
We should really standardize on whether "" or None means unspecified.

2023-11-27 19:40 UTC, irfanshar commented on src/makei/init_project.py
> +def update_json_field(pathToJsonFile: str, updateKey1: str, updateVal: str, updateKey2: str = "") -> None:
If the value of ```updateKey2``` is "", then we are updating a top-level key.
For example,
```
{
  updateKey1: updateVal
}
```

If the value of ```updateKey2``` is NOT "", then we are updating an inner key.
For example,
```
{
    updateKey1: 
        {
           updateKey2: value
        }
}
```

However, it seems as if ```None``` means unspecified in other parts of the project.
I will make the necessary changes to update the instances where "" means unspecified to ```None```.

2023-12-06 15:11 UTC, edmundreinhardt commented on src/makei/build.py
> +        dir_var_map = {Path('.'): IBMiJson.from_values(self.iproj_json.tgt_ccsid)}
@irfanshar did you respond to this comment

2023-12-08 21:42 UTC, irfanshar commented on src/makei/build.py
> +        dir_var_map = {Path('.'): IBMiJson.from_values(self.iproj_json.tgt_ccsid)}
@edmundreinhardt Yes, my mistake, I restored objlib being passed in

2023-12-12 22:11 UTC, edmundreinhardt approved these changes
Looks good

2023-12-12 22:11 UTC, merged