Fix/build sql mbr text
IBM/ibmi-bob pull request #289
Opened 2024-01-15 21:59 UTC by irfanshar

2024-01-16 14:55 UTC, edmundreinhardt requested changes

2024-01-16 14:55 UTC, edmundreinhardt commented on src/scripts/launch
> +cl "$text_command"
Doesn't this assume that the text_command is always set, but it is only set for SQL

2024-01-16 14:59 UTC, edmundreinhardt commented on src/scripts/launch
> +cl "$text_command"
Do you have to have to check if text_command is set and assume it is not set if only 8 parms are passed

2024-01-17 11:11 UTC, edmundreinhardt commented
We have a problem, the MEMBER text is updated but not the O BJECT text which is what is desired

2024-01-17 11:13 UTC, edmundreinhardt commented
> We have a problem, the MEMBER text is updated but not the O BJECT text which is what is desired

<img width="555" alt="image" src="https://github.com/IBM/ibmi-bob/assets/11184579/69447541-791c-4416-99a2-b399a9e5ab75">

<img width="197" alt="image" src="https://github.com/IBM/ibmi-bob/assets/11184579/eb6d927f-2553-44f7-bb7a-3fb41a625d58">

2024-01-17 11:20 UTC, edmundreinhardt commented
> > We have a problem, the MEMBER text is updated but not the O BJECT text which is what is desired
> 
 Fixed using CHGOBJD
 
 Now is is necessary to be so far indented for SQL and free RPG?

2024-01-17 13:03 UTC, edmundreinhardt commented
I switched to CHGOBJD and updated the bob-recursive-example to test it.  Some objects still not working.

2024-01-17 14:53 UTC, irfanshar commented
> > > We have a problem, the MEMBER text is updated but not the O BJECT text which is what is desired
> 
> Fixed using CHGOBJD
> 
> Now is is necessary to be so far indented for SQL and free RPG?

The indentation isn't necessary, but was done to match ARCAD's example https://github.com/aecspades/arcad-example/blob/master/QSQLSRC/ARTIINF.TABLE

2024-01-17 18:34 UTC, edmundreinhardt approved these changes
looks good

2024-01-17 18:37 UTC, merged