Feature/wildcard support
IBM/ibmi-bob pull request #346
Opened 2024-10-14 23:19 UTC by irfanshar

2024-10-17 15:16 UTC, edmundreinhardt requested changes
This is great! do you have any tests defined?  Say callng rules_mk.from_str and testing the results RulesMk object?

2024-11-08 15:50 UTC, edmundreinhardt commented on src/makei/rules_mk.py
> +
Does this logic handle when := is not surrounded by spaces
i.e.
var:=value
instead of
var := value

2024-11-08 15:51 UTC, edmundreinhardt commented on src/makei/rules_mk.py
> +                # rules_mk variable definition
let's put and example here to illustrate i.e.
# var := value

2024-11-08 16:37 UTC, edmundreinhardt requested changes
We need to add tests

2024-11-08 16:37 UTC, edmundreinhardt commented on src/makei/rules_mk.py
>                      # private variable definition
target: var := $(value)

2024-11-08 16:37 UTC, edmundreinhardt commented on src/makei/rules_mk.py
> +                    # Wildcard %.TARGET: %.SOURCE DEP1 DEP2
Test if we handle wildcard recipes that span lines i.e.
```
%.MODULE: %.RPGLE DEP1.FILE \
                      DEP2.FILE

2024-11-08 16:37 UTC, edmundreinhardt commented on src/makei/rules_mk.py
> +        for target_ext, object_ext, dependencies in wildcard_targets:
second in list should be named `source_ext` not `object_ext`

2024-11-08 20:24 UTC, edmundreinhardt commented
Tested the following to prove that we can't assume that ':=' will be space delimited
```
CURRENT:=V7R5

all: 
	echo $(CURRENT)
```
gmake all produces `V7R5` therefore we need to support this

2024-12-06 00:37 UTC, SanjulaGanepola commented
@edmundreinhardt Can you review this PR and suggest any more edge cases to test. I resolved the test case issues we found earlier. All tests are now passing and bob-recursive-example build is still good. If all looks good, we can merge and release.

![image](https://github.com/user-attachments/assets/a3c697e9-7981-4078-8335-11007b2ad8e6)
![image](https://github.com/user-attachments/assets/a63dca55-1c6c-4c2b-830f-f2ed2a159ac4)

2024-12-06 01:21 UTC, edmundreinhardt commented on src/makei/rules_mk.py
> +            pattern = re.compile(r'^[^:]*(:=|=).*')
add a comment what regex

2024-12-06 01:21 UTC, edmundreinhardt commented on tests/data/rules_mks/wildcard/wildcard.rules.mk
> +CURRENT:=V7R5
also test 'foo=val' for regular =

2024-12-06 02:21 UTC, SanjulaGanepola commented
@edmundreinhardt I addressed the comments. I believe some of the comments you were going to leave when we were reviewing did not get posted here. I think I caught everything however. Let me know if anything was missed.

2024-12-06 03:26 UTC, edmundreinhardt approved these changes

2024-12-06 03:27 UTC, merged